import { test, expect } from "@playwright/test"

for (const width of [320, 390, 564, 720]) test(`compact mobile header, footer and vertical-only directory at ${width}`, async ({ page }) => {
  await page.setViewportSize({ width, height: 994 })
  const errors: string[] = []
  page.on("console", message => { if (message.type() === "error" && message.text().includes("Unexpected text node")) errors.push(message.text()) })
  await page.goto("/")
  await expect(page.getByRole("textbox", { name: "what are you building?" })).toHaveCount(0)
  const search = page.getByRole("button", { name: "Search resources", exact: true })
  const menu = page.getByRole("button", { name: "Browse categories" })
  expect((await search.boundingBox())!.y).toBe((await menu.boundingBox())!.y)
  expect(await menu.evaluate(el => getComputedStyle(el).backgroundColor)).toBe("rgba(0, 0, 0, 0)")
  expect(await menu.evaluate(el => getComputedStyle(el).borderTopWidth)).toBe("0px")
  const pane = page.locator(".directory").locator("..")
  expect((await pane.boundingBox())!.y).toBeLessThan(140)
  for (const name of ["Aceternity UI", "SHSF UI Cards", "Animate UI", "Voxlet UI", "Cult UI", "Fancy Components"]) await page.getByRole("checkbox", { name: `Select ${name} for your stack`, exact: true }).click()
  await expect.poll(async () => (await page.locator(".split-pane-heading").boundingBox())!.y).toBeGreaterThan(670)
  const anchor = page.locator(".mobile-visitor-anchor")
  const dock = page.locator(".globe-dock")
  await expect.poll(async () => Math.abs((await dock.boundingBox())!.y - (await anchor.boundingBox())!.y)).toBeLessThan(2)
  const credits = (await page.locator(".footer-credits").boundingBox())!
  const trigger = (await dock.boundingBox())!
  expect(credits.x + credits.width).toBeLessThanOrEqual(trigger.x)
  await pane.hover()
  await page.mouse.wheel(400, 250)
  await expect.poll(() => pane.evaluate(el => el.scrollTop)).toBeGreaterThan(100)
  expect(await pane.evaluate(el => el.scrollLeft)).toBe(0)
  expect(await page.evaluate(() => document.documentElement.scrollWidth)).toBe(width)
  const tabs = page.getByRole("tablist", { name: "Your selected resources" })
  expect(await tabs.evaluate(el => el.scrollWidth)).toBeGreaterThan(await tabs.evaluate(el => el.clientWidth))
  await page.mouse.move(0, 0)
  await page.screenshot({ path: `test-results/compact-mobile-${width}.png` })
  await menu.click()
  const nav = page.getByRole("navigation", { name: "Categories" })
  const label = nav.getByText("UI Components", { exact: true })
  expect(await label.evaluate(el => getComputedStyle(el).fontSize)).toBe("16px")
  await page.screenshot({ path: `test-results/mobile-large-navigation-${width}.png` })
  await menu.click()
  expect(errors).toEqual([])
})

test("mobile search preserves drafts, submits once, remembers real searches and restores focus", async ({ page }) => {
  await page.setViewportSize({ width: 390, height: 844 })
  let requests = 0
  await page.route("**/api/recommend", route => { requests++; return route.fulfill({ json: { picks: [] } }) })
  await page.goto("/")
  const trigger = page.getByRole("button", { name: "Search resources", exact: true })
  await trigger.click()
  const dialog = page.getByRole("dialog", { name: "Describe your next project" })
  const input = dialog.getByRole("textbox", { name: "what are you building?" })
  await expect(input).toBeFocused()
  await expect(dialog.getByText("Recent searches")).toHaveCount(0)
  await input.fill("animated portfolio")
  await page.getByRole("button", { name: "Close search", exact: true }).click()
  await expect(dialog).toHaveCount(0)
  await expect(trigger).toBeFocused()
  await trigger.click()
  await expect(input).toHaveValue("animated portfolio")
  await page.getByRole("button", { name: "Pick resources", exact: true }).click()
  await expect(dialog).toHaveCount(0)
  expect(requests).toBe(1)
  await expect(page.getByRole("heading", { name: "Jev Picks" })).toBeInViewport()
  await trigger.click()
  await expect(dialog.getByRole("button", { name: "animated portfolio", exact: true })).toBeVisible()
  await dialog.getByRole("button", { name: "Clear search" }).click()
  await expect(input).toHaveValue("")
  await dialog.getByRole("button", { name: "animated portfolio", exact: true }).click()
  await expect(input).toHaveValue("animated portfolio")
  await expect.poll(() => page.locator("#mobile-search-overlay").evaluate(el => Number(getComputedStyle(el).opacity))).toBeGreaterThan(0.99)
  expect(await page.locator("#mobile-search-overlay").evaluate(el => getComputedStyle(el).backgroundColor)).not.toBe("rgba(0, 0, 0, 0)")
  await page.screenshot({ path: "test-results/mobile-search-recents.png" })
  await page.keyboard.press("Escape")
  await expect(dialog).toHaveCount(0)
  await expect(trigger).toBeFocused()
  await expect(page.locator(".directory")).not.toHaveAttribute("inert", "")
})
